### PR TITLE
Fix MMU needs user attention Statistics error

### LINKED ISSUE #1849: Elapsed time is much too high after print
See photo at https://i.imgur.com/XUooqti.jpg.  
This print took about 18 hours, but printer thinks it was 1143 hours.
Printer: MK3/S + MMU2/S. 

Gcode is the MMU2S version from https://www.prusaprinters.org/prints/168-universal-auto-rewind-spool-holder-mm/files

### LINKED ISSUE #1922: total print time statistics (FW 3.7.2 RC1)
Total print time is a bit off ... it shows more than 500 days on a printer that is not even one year old yet (assembled in August 2018).
IMG_20190615_095407

### PR DESCRIPTION
**Pull request by leptun**
If you encounter a "MMU needs user attention" error, fix the issue and let the print finish, then the total print time in Statistics will show bogus numbers. This PR prevents this from happening.
Closes #1849 
Closes #1922 

PFW-1070

### CODE REVIEW

File: Firmware/mmu.cpp [hunk 1]
```diff
@@ -1572,18 +1572,7 @@ void mmu_continue_loading(bool blocking)
...
-            if (current_position[Z_AXIS] > Z_MAX_POS) current_position[Z_AXIS] = Z_MAX_POS;
-            plan_buffer_line_curposXYZE(15, active_extruder);
-            st_synchronize();
-
-            //Move XY to side
-            current_position[X_AXIS] = X_PAUSE_POS;
-            current_position[Y_AXIS] = Y_PAUSE_POS;
-            plan_buffer_line_curposXYZE(50, active_extruder);
-            st_synchronize();
+            long_pause();
```
Comment (DRracer) [inline Firmware/mmu.cpp:1575]: Hmm, long_pause contains retraction and turns the fan off
Is it really equivalent (or better) compared to the original code?

**Review by DRracer — APPROVED** [review]
