### PR TITLE
#2089 fix sheet rename cursor

### LINKED ISSUE #2089: Sheet rename cursor does not clear
Found in 3.8.0-RC1, Mk3S.

The caret below the selected letter does not clear when pushing the knob to move to the next letter.

IMG_0001

### PR DESCRIPTION
**Pull request by vintagepc**
Fixes #2089 

No longer leaves a cursor trail: 

image

### CODE REVIEW

File: Firmware/ultralcd.cpp [hunk 1]
```diff
@@ -6733,7 +6733,15 @@ static void lcd_rename_sheet_menu()
     {
         lcd_putc(menuData->name[i]);
     }
-    lcd_set_cursor(menuData->selected, 1);
+    if (menuData->selected>0)
+    {
+	    lcd_set_cursor(menuData->selected-1, 1);    
+	    lcd_putc(' ');
```
Comment (gudnimg) [inline Firmware/ultralcd.cpp]: Could be optimised with `lcd_putc_at(menuData->selected-1, 1, ' ');` ;)

Comment (vintagepc) [reply Firmware/ultralcd.cpp]: Does that put the cursor back in the next character position when it is done?

Comment (gudnimg) [reply Firmware/ultralcd.cpp]: Yes exactly, it should do the same. Should save a few bytes to call one function instead of two. Not critical but should save some bytes

Comment (vintagepc) [reply Firmware/ultralcd.cpp]: Done, and further optimized to remove the if/else

**Review by gudnimg — APPROVED** [review]
Looks good to me

**Review by DRracer — APPROVED** [review]
