### PR TITLE
`crashdet_cancel()` doesnt cleanup all variables when USB printing

### LINKED ISSUE #4324: [BUG] Mk3S+ with MMU3 not re-heating after safety timer
**Printer type**
Mk3S+
**Printer firmware version**
3.13.0

**MMU upgrade**
MMU3
**MMU upgrade firmware version** 
3.0.0

**SD card or USB/Octoprint** 
PrusaLink 0.7.0

**Describe the bug**
 The printer detected a crash, repeatedly, so it paused. After confirming I didn't want to continue with the print, the MMU tried to pull the filament out of the nozzle, as with any other end of the print, however, the nozzle was cold at this point (30 min safety timer) yet the printer ignored that and never reheated the nozzle so the MMU triggered an error - filament in Finda.
 The only way out of this was restarting the printer as the LCD menu is not accessible through the MMU's error message.
  
**To Reproduce**
  Trigger the 30-minute safety timer where the filament is still in the nozzle (so not after filament runout for example).
  
**Expected behaviour**
The printer should re-heat the nozzle before any following action.
  
**G-code**
The issue is not G-code relevant.

### PR DESCRIPTION
**Pull request by gudnimg**
This function doesn't look correct to me 🤔 I would think that this should behave similarly as when stopping the print via the LCD. This PR is my proposed improvement, un-tested at the moment.

Changed `UnconditionalStop()` to not close the SD card file if we're using Octoprint. Then there shouldnt be any file open.

Some of the variables which were not reset:
`isPrintPaused`
`pause_time`
`saved_start_position`
`saved_printing_type`

It seems like the bed heater could also be left enabled?

Fixes https://github.com/prusa3d/Prusa-Firmware/issues/4324

Change in memory:
Flash: -28 bytes
SRAM: 0 bytes

### CODE REVIEW

**Comment by wavexx** [comment]
I generally agree here, I think this has always been overlooked recently

File: Firmware/Marlin_main.cpp [hunk 1]
```diff
@@ -640,16 +640,9 @@ void crashdet_recover()
...
-	tmc2130_sg_stop_on_crash = true;
-	if (saved_printing_type == PRINTING_TYPE_SD) {
-		print_stop();
-	}else if(saved_printing_type == PRINTING_TYPE_USB){
-		SERIAL_ECHOLNRPGM(MSG_OCTOPRINT_CANCEL); //for Octoprint: works the same as clicking "Abort" button in Octoprint GUI
-		cmdqueue_reset();
-	}
+/// Crash detection cancels the print
+void crashdet_cancel() {
+    print_stop();
```
Comment (wavexx) [inline Firmware/Marlin_main.cpp:644]: The only difference I see here is that before we would send MSG_OCTOPRINT_CANCEL, but now we first call UnconditionalStop(), which clears card.sdprinting, so the condition in print_stop at ultralcd.cpp:5582 is always false...

this seems like a pre-existing bug?

**Review by wavexx — DISMISSED** [review]
I agree here, I think this has always been overlooked

Maybe we can also call directly print_stop() when handling the CRASHDET_CANCEL command in Marlin_main.cpp:4035.

File: Firmware/Marlin_main.cpp (hunk 1 above)
Comment (gudnimg) [reply Firmware/Marlin_main.cpp:644]: I just looked at it now and you're right!

image
image

Comment (gudnimg) [reply Firmware/Marlin_main.cpp:644]: I added another commit to resolve this hopefully.

**Comment by gudnimg** [comment]
I pushed another commit which optimizes setting the crash detection on or off.

File: Firmware/Marlin_main.cpp (hunk 1 above)
Comment (3d-gussner) [reply Firmware/Marlin_main.cpp:644]: @gudnimg @wavexx is this solved? If so please use Resolve conversation to make it easier to merge.

**Comment by gudnimg** [comment]
Adding 🚧 to the title as this PR is not tested

File: Firmware/Marlin_main.cpp [hunk 2]
```diff
@@ -631,20 +631,17 @@ void crashdet_detected(uint8_t mask)
 
 void crashdet_recover()
 {
-  if (!print_job_timer.isPaused()) crashdet_restore_print_and_continue();
-  if (lcd_crash_detect_enabled()) tmc2130_sg_stop_on_crash = true;
+	if (!print_job_timer.isPaused()) crashdet_restore_print_and_continue();
```
Comment (3d-gussner) [inline Firmware/Marlin_main.cpp:634]: Change the line 620 `uint8_t yesno = lcd_show_yes_no_and_wait(false);` to `uint8_t yesno = lcd_show_yes_no_and_wait(false, LCD_LEFT_BUTTON_CHOICE);`
so RECOVER CRASH default is YES.
I think an accidental knob click should try to recover the crash instead of killing it.

**Review by 3d-gussner — CHANGES_REQUESTED** [review]
Tested on MK404
Started USB print
- [X] Triggered crash recovers
- [X] Triggered crash stop, stops the print correctly on printer and host
- [X] Crash det. [OFF] does work as it ignores the crashes

Approved only change I would like to see is that Recover crash default is YES

**Review by 3d-gussner — APPROVED** [review]
