### PR TITLE
PFW-1052: "Unknown z" improvements

### LINKED ISSUE #1748: Z raised above maximum when issuing "G28" (autohome) or filament autoload from maximum height
"G28" will home X, Y, then move the plate while raising Z before homing Z itself.

If you issue G28 from the condition in which the printer is already at max height, Z is just pushed against the Z-tops in two separate moves.

I assume that checking the current Z height is intentionally avoided while homing, but then this is one condition where I would expect crash detection on Z to work.

Is it possible to perform crash-detection on Z?

The same issue is true if you autoload a filament from a high Z. The filament autoload procedure will raise Z the first time, even if Z hasn't been homed yet.

### PR DESCRIPTION
**Pull request by wavexx**
This PR fixes #1748

I introduce a new function, raise_z_above to move Z carefully when the current position is potentially unknown, making it useful for several lcd functions which can be issued just after starting the printer.

raise_z_above uses stallguard when the Z position is unknown and a regular move otherwise. 
The following conditions will now use raise_z_above:

* during filament loading/unloading, for blob clearance.

* extruder spacing when preheating. This is done to avoid buildplate marks on the PEI sheet, which is something I have, as I often preheat from the menu and sometimes come back late.

* before homing to avoid scratching the build plate. This was already done, but incorrectly.

In the original homing sequence, G28 will raise Z, home XY, then raise again unconditionally. If the printer was already at max height, a G28 **will** crash twice against the Z tops. The same was true during filament unloading if the printer was reset and issued an unload from the LCD.

raise_z_above is a no-op if the position is already above the target, which avoids several useless moves also when homing the axes independently.

### CODE REVIEW

**Comment by wavexx** [comment]
Now also fixes #1668 and #1410 (which seems identical, both pointing to mmu_lcd_load_to_nozzle), superseding pr #1767. I cannot verify the MMU2 behavior myself though.

**Comment by wavexx** [comment]
@mkbel Noticed dad2065da623b1f1eb704de2223fcaed9b96c281 now conflicts with this. Since lcd_mmu_load_to_nozzle can probably be called without Z being homed yet, I assume the above still applies.

It doesn't raise while extruding since SG can be on, but I could definitely also include this option by combining both moves if Z is known, and doing them separately if not.

**Comment by wavexx** [comment]
I updated the PR to combine raising and slow extrusion, as "rise_z" did.
The moves are only combined only when Z height is known.

File: Firmware/Marlin_main.cpp [hunk 1]
```diff
@@ -3166,10 +3200,7 @@ void gcode_M701()
 		plan_buffer_line(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS], 400 / 60, active_extruder); //fast sequence
 		st_synchronize();
 
-		marlin_rise_z();
-		current_position[E_AXIS] += 30;
```
Comment (leptun) [inline Firmware/Marlin_main.cpp:3184]: Why didn't you keep this line? With these changes my filament only loads to the nozzle and doesn't extrude any filament. I have to click NO and only then does it start extruding

**Comment by wavexx** [comment]
On Fri, Jul 12 2019, leptun wrote:
> -		marlin_rise_z();
> -		current_position[E_AXIS] += 30;

Good thing you noticed. Probably shuffled during one of the rebases with
the following commit.

**Comment by wavexx** [comment]
Updated

**Review by DRracer — APPROVED** [review]
