### PR TITLE
Fix clicking noise during Toolchange when E-cool mode is enabled

### LINKED ISSUE #3497: [BUG] Experimental feature "E-cool mode" has odd effects on extruder on MMU2S load sequence.
**Printer type** - MK3S+
**Printer firmware version** -  3.11.0

**MMU upgrade** - MMU2S
**MMU upgrade firmware version** - 1.0.6

**SD card or USB/Octoprint**
  Octoprint

**Describe the bug**
  With E-cool mode enabled in the experimental features menu, the loading sequence causes the extruder to make a clicking sound.
  
**To Reproduce**
  With an MK3S+ MMU2S printer, enable the E-cool mode in the experimental features menu, then do a first-layer calibration on any filament, listen to the extruder during the load sequence.
  
**Expected behavior**
  No observable difference from E-cool mode being off.
  
**G-code**
  On-board first-layer calibration sufficient to reproduce issue.

**Video**
  [Video of issue on YouTube (apologies for the vertical video).](https://www.youtube.com/shorts/Sud9mxOqvwY)

### PR DESCRIPTION
**Pull request by gudnimg**
Idea to fix https://github.com/prusa3d/Prusa-Firmware/issues/3497 by using the re-written MMU code on the MK3 side (3.13).

Kudos goes to @leptun for this idea, this is my attempt at implementing it.

Currently we are queuing many small 2 mm E-moves until the filament sensor triggers. We do this because we never abort any queued moves, so making small 2 mm moves ensures we do not move the E-motor more than 2 mm past the filament sensor.

Unfortunately, when E-cool mode is enabled, the E-motor will create audible clicking sounds (similar one hears during jam or a loose grub screw). A workaround for this is to queue one or more very long moves. Where _very long_ is something of the order of hundreds of millimeters. I have it set to 350 mm but it's just a random constant really. Keep in mind the firmware will block too large E-moves, if I recall correctly it was anything above > 450 mm (see `PREVENT_LENGTHY_EXTRUDE`)

In order to use very long moves, we must somehow stop the E-motor from moving once the filament sensor triggers. In other words, throw away what's left of the current E-motor move. For this simple purpose  we can use `planner_abort_hard()` but we must set `planner_aborted` to `false` afterwards because the code architecture does not allow the main `loop()` to run until the Toolchange command is done processing.

Video demonstration
=====

**BEFORE:** https://youtu.be/4BohuSCnrIU (Notice the clicking sound when the MMU changes state from Loading to Gears, to Loading to Fsensor)

**AFTER:** https://youtu.be/K3Io_GBRNfo (Clicking noise is gone, sound is smooth like normal) 

------

TO-DO list:
=====

- [x] Run a multi-color print with at least 100 toolchanges
- [x] Add more comments to the code, e.g. document function and our intention with the abort. It's only for E-moves.

-----

Change in memory:
Flash: +18 bytes
SRAM: 0 bytes

### CODE REVIEW

**Comment by gudnimg** [comment]
Printed 5 Catan Seafarers ships. Its a handy test print which I use often since it doesnt take more than 5 hours. 

The results are good. 

On top of this PR I added two other PRs to test:

* https://github.com/prusa3d/Prusa-Firmware/pull/4070
* https://github.com/prusa3d/Prusa-Firmware/pull/3962

This print might not be the best to test the acceleration PR but I wanted to print something with it anyway. 

The boats look good 😃 E-cool mode was active the entire time. 

image

image

All 5 MMU slots were loaded with filament. But in this print only 3 colors are used: Blue, White and Yellow.

**Comment by leptun** [comment]
Test print successful also here. 2 colors, 5 loaded. 133 toolchanges. No issues in the purge tower.

image

File: Firmware/mmu2.cpp [hunk 1]
```diff
@@ -1048,7 +1054,7 @@ void MMU2::OnMMUProgressMsgSame(ProgressCode pc) {
             case FilamentState::NOT_PRESENT:
                 // fsensor not triggered, continue moving extruder
                 if (!planner_any_moves()) { // Only plan a move if there is no move ongoing
-                    MoveE(2.0f, MMU2_LOAD_TO_NOZZLE_FEED_RATE);
+                    MoveE(350.0f, MMU2_LOAD_TO_NOZZLE_FEED_RATE);
```
Comment (leptun) [inline Firmware/mmu2.cpp:1062]: Please add the note about the long extrusion prevention here.

**Review by leptun — APPROVED** [review]

File: Firmware/mmu2.cpp (hunk 1 above)
Comment (gudnimg) [reply Firmware/mmu2.cpp:1062]: Thanks I forgot about it

Comment (gudnimg) [reply Firmware/mmu2.cpp:1062]: Done
