### PR TITLE
MK3: TM: Prevent lockout on invalid model values

### LINKED ISSUE #3630: [BUG] TM errors without a running print cannot be resumed
**Printer type** - n/a
**Printer firmware version** -  3.12+

**MMU upgrade** - n/a
**MMU upgrade firmware version** - n/a

**SD card or USB/Octoprint**
n/a

**Describe the bug**
If a Temperature Model error is triggered when there is no current print, the printer enters the "Stopped" state (as it would while printing). But since there's no print, it's impossible to "resume".
  
**To Reproduce**
`M310 S1 E0.01` will immediately enter this state.

**Expected behavior**
It's correct that a thermal error should still prevent the serial to work, just like while printing.

This can be actually _worse_ than a normal thermal error, since it means that the heater managed to trigger a problem not only while being preheated, but also potentially while being off.

In such case getting stuck in a "THERMAL ERROR - PLEASE RESET" like other thermal features might actually be good thing to do.

### PR DESCRIPTION
**Pull request by wavexx**
If the model is changed to invalid values (by manually running ``M310 C0.01`` for example) the printer will enter a continuous state of thermal error where 1) the LCD is unusable and 2) the serial is disabled. This cannot be undone except for a factory reset.

Allow again to use the menus after a thermal error. Since the thermal model is managing the heaters, the user can't worsen the situation. This can be used to run gcode from the SD.

Allow M310 to bypass the serial lock. M310 doesn't control heaters, and can't be used to bypass the stopped state, so it's safe to run in an emergency situation to reset the model.

~This is still incomplete though: if the thermal anomaly is constantly triggering (as happens with wrong values), even though the menus are unlocked, the error will continuously force redisplay, preventing you from doing anything.~

- [X] Create cherry-pick PR to [MK3_3.12 branch](https://github.com/prusa3d/Prusa-Firmware/pull/3845)

### CODE REVIEW

**Review by 3d-gussner — CHANGES_REQUESTED** [review]
Please review and add https://github.com/wavexx/Prusa-Firmware/pull/10

Tested this on MK404 which does directly into TM Error.
- Sending `M310 S0` :heavy_check_mark: 
  - But after reset, which is the only option printer is still locked
    - With the PR above I am able to disable the temp model and save it, so next time it reboots it stays disabled.

File: Firmware/cmdqueue.cpp [hunk 1]
```diff
@@ -422,25 +424,24 @@ void get_command()
 			  cmdbuffer[bufindw + CMDHDRSIZE] = '$';
 		}
         // if we don't receive 'N' but still see '*'
-        if ((cmdbuffer[bufindw + CMDHDRSIZE] != 'N') && (cmdbuffer[bufindw + CMDHDRSIZE] != '$') && (strchr(cmdbuffer+bufindw+CMDHDRSIZE, '*') != NULL))
+        if ((*cmd_head != 'N') && (cmdbuffer[bufindw + CMDHDRSIZE] != '$') && (strchr(cmd_start, '*') != NULL))
```
Comment (DRracer) [inline Firmware/cmdqueue.cpp]: Why wasn't `cmdbuffer[bufindw + CMDHDRSIZE]` also changed to `*cmd_head`? I don't see a difference yet...

File: Firmware/cmdqueue.cpp [hunk 2]
```diff
@@ -422,25 +424,24 @@ void get_command()
...
+        if(strcmp_P(cmd_start, PSTR("M112")) == 0)
           kill(MSG_M112_KILL, 2);
+
         // Handle the USB timer
-        if ((strchr_pointer = strchr(cmdbuffer+bufindw+CMDHDRSIZE, 'G')) != NULL) {
-            if (!IS_SD_PRINTING) {
-                usb_timer.start();
-            }
-        }
+        if ((*cmd_start == 'G') && !IS_SD_PRINTING)
```
Comment (DRracer) [inline Firmware/cmdqueue.cpp]: suggest parentheses around `IS_SD_PRINTING` as it is a macro and unintentional change of it may cause hard-to-debug issues in the future

**Review by DRracer — APPROVED** [review]
Looks correct to me, just 2 minor stylistic questions. Otherwise I don't see any further issues with these changes

File: Firmware/cmdqueue.cpp (hunk 1 above)
Comment (wavexx) [reply Firmware/cmdqueue.cpp]: Probably because I removed it entirely on #3823. I will fix this

**Comment by wavexx** [comment]
Regarding https://github.com/wavexx/Prusa-Firmware/pull/10 I would handle it differently. We need to allow the user to unlock the printer from the LCD.

Besides adding code in a hot path, M500 can save garbage state, and allowing the command there will make it available also while breaking the paused protocol, something I'm really not keen on.

**Comment by wavexx** [comment]
We the latest commits we do the following:

- Repeated thermal model warnings/errors now do not prevent menu access
- Only partial menu access is available: preheat/filament/calibrate actions are disabled
- The user can clear a thermal error by using "Acknowledge error". This works for a one-time error, and will resume USB serial processing as expected in the same way aborting/resuming a thermal error pause does.
- "Print from SD" is now available during a thermal error, and a new print will implicitly *clear* the error state. This is allowed as an escape hatch to run g-code containing "M310 S0" to disable the model. If the model is still running, the SD print will still be interrupted pretty fast, so it should pose no threat.

File: Firmware/messages.cpp [hunk 3]
```diff
@@ -169,6 +169,7 @@ extern const char MSG_PAUSED_THERMAL_ERROR[] PROGMEM_I1 = ISTR("PAUSED THERMAL E
 #ifdef TEMP_MODEL
 extern const char MSG_THERMAL_ANOMALY[] PROGMEM_I1 = ISTR("THERMAL ANOMALY");////MSG_THERMAL_ANOMALY c=20
 extern const char MSG_TM_NOT_CAL[] PROGMEM_I1 = ISTR("Temp model not calibrated yet.");////MSG_TM_NOT_CAL c=20 r=4
+extern const char MSG_ACK_ERROR[] PROGMEM_I1 = ISTR("Acknowledge error");////MSG_ACK_ERROR c=17
```
Comment (3d-gussner) [inline Firmware/messages.cpp]: A menu can be `c=18`
The message may not be that clear to the users.
```
01234567890123456789
>Clear TM error    ➔
>Confirm TM error  ➔
>Unlock TM error   ➔

**Comment by wavexx** [comment]
This fixes #3630

File: Firmware/messages.cpp [hunk 4]
```diff
@@ -169,6 +169,7 @@ extern const char MSG_PAUSED_THERMAL_ERROR[] PROGMEM_I1 = ISTR("PAUSED THERMAL E
 #ifdef TEMP_MODEL
 extern const char MSG_THERMAL_ANOMALY[] PROGMEM_I1 = ISTR("THERMAL ANOMALY");////MSG_THERMAL_ANOMALY c=20
 extern const char MSG_TM_NOT_CAL[] PROGMEM_I1 = ISTR("Temp model not calibrated yet.");////MSG_TM_NOT_CAL c=20 r=4
+extern const char MSG_TM_ACK_ERROR[] PROGMEM_I1 = ISTR("Clear TM error");////MSG_TM_ACK_ERROR c=18
```
Comment (3d-gussner) [inline Firmware/messages.cpp:172]: Adding new message needs an update of the pot and po files.
Also the new message should be translated.
Do want to do that in a separate PR?
Splitting "unblocks" this PR as we don't need to wait for the translations, which may take a while.

Comment (wavexx) [reply Firmware/messages.cpp:172]: Why would it block it?

**Review by 3d-gussner — APPROVED** [review]
Works well on MK404 and real printer.
On MK404 after factory reset I am able to recover from TM error and "unlock" the printer. This solves the worst case scenario of locking out users.

File: Firmware/messages.cpp (hunk 4 above)
Comment (3d-gussner) [reply Firmware/messages.cpp:172]: Because we have to wait for the translations
